import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import Sidebar from "@/components/sidebar";
import dayjs from "@/utils/dayjs";

export const metadata: Metadata = {
  title: "Deschamps News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const date = dayjs().format("YYYY-MM-DD");

  return (
    <html lang="pt-br">
      <body className="min-h-screen flex justify-center antialiased">
        <aside className="w-[24rem] flex-shrink-0">
          <Sidebar date={date} />
        </aside>

        <main className="w-[36rem] overflow-y-auto">{children}</main>

        <ToastContainer position="bottom-left" hideProgressBar={true} />
      </body>
    </html>
  );
}
